services:
    laravel.test: 
        build:
            context: './vendor/laravel/sail/runtimes/8.5'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: 'sail-8.5/app'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
             mysql:
                condition: service_healthy #Espera a que la base de datos esté lista antes de iniciarse el servicio ya que la base de datos se crea desde cero en este archivo.
             mailpit:
                condition: service_started
        entrypoint: 
            #Primero se comprueba si está instalado el composer comprobando si el directorio /vendor/autoload.php existe. Si no es el caso, se instala.
            #Posteriormente se comprueba si el archivo .env existe. Si no es así, se crea a partir del .env.example.
            #A continuación se compprueba si la APP_KEY de la aplicación existe y si no es así, se genera una nueva.
            #Por último, se ejecutan las migraciones para crear las tablas de la base de datos y se generan nuevos registros a partir de los seeders de Laravel.

            ["sh", "-c", "
            if [ ! -d vendor/autoload.php ]; then
                composer install --no-interaction --prefer-dist --optimize-autoloader;
            fi;
            if [ ! -f .env ]; then
                cp .env.example .env;
            fi;
            if ! grep -q 'APP_KEY=base64' .env; then
                php artisan key:generate --force;
            fi;

            chmod -R 777 storage bootstrap/cache;
            
            php artisan migrate:fresh --seed --force;
            exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
            "]
            #En la línea 48 debe de borrarse :fresh y --seed para que, tras el primer incio del contenedor no se borre la base de datos ni los registros.        
    mysql:
        image: 'mysql:8.0.34'
        ports:
            - '${FORWARD_DB_PORT:-5555}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_EXTRA_OPTIONS: '${MYSQL_EXTRA_OPTIONS:-}'
        volumes:
            - 'db-data:/var/lib/mysql'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
    mailpit:
        image: axllent/mailpit:latest
        networks:
            - sail
        ports:
            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
            - '${FORWARD_MAILPIT_WEB_PORT:-8025}:8025'
networks:
    sail:
        driver: bridge
volumes:
    db-data:
        driver: local
